version: '3.7'
services:
  anthe:
    build:
      context: .
      dockerfile: Dockerfile
    image: lukaswire/anthe
    container_name: anthe
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - anthe-net

  db:
    image: postgres:12.2
    container_name: anthe-db
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - anthe-net
    volumes:
      - anthe-db-vol:/var/lib/postgresql/data/


networks:
  anthe-net:
    driver: bridge

volumes:
  anthe-db-vol: